CREATE USER weto WITH PASSWORD 'weto';
CREATE DATABASE weto5_master WITH OWNER = weto ENCODING = 'UTF-8' LC_COLLATE = 'fi_FI.UTF-8' TEMPLATE = template0;
CREATE DATABASE weto5_kurssi WITH OWNER = weto ENCODING = 'UTF-8' LC_COLLATE = 'fi_FI.UTF-8' TEMPLATE = template0;
